-- ============================================================
-- SenCye prototype schema
-- Jalankan di Supabase SQL Editor setelah membuat project.
--
-- CATATAN:
-- Policy di bawah dibuat untuk DEMO/LOMBA agar frontend tanpa login
-- dapat diuji lintas perangkat. Untuk production, WAJIB ganti dengan
-- Supabase Auth + RLS berbasis user_id/companion_id.
-- ============================================================

create table if not exists public.voice_notes (
    id bigint generated by default as identity primary key,
    companion_id text not null,
    audio_url text not null,
    duration_ms integer default 0,
    sender_role text not null default 'user',
    created_at timestamptz not null default now()
);

alter table public.voice_notes enable row level security;

drop policy if exists "demo voice insert" on public.voice_notes;
drop policy if exists "demo voice select" on public.voice_notes;

create policy "demo voice insert"
on public.voice_notes
for insert
to anon
with check (true);

create policy "demo voice select"
on public.voice_notes
for select
to anon
using (true);

insert into storage.buckets (id, name, public)
values ('voice-notes', 'voice-notes', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "demo voice storage insert" on storage.objects;
drop policy if exists "demo voice storage select" on storage.objects;

create policy "demo voice storage insert"
on storage.objects
for insert
to anon
with check (bucket_id = 'voice-notes');

create policy "demo voice storage select"
on storage.objects
for select
to anon
using (bucket_id = 'voice-notes');


alter table public.voice_notes add column if not exists sender_role text not null default 'user';
